### ISSUE TITLE
Incorrect environment variable for creating kp secrets with dockerhub

### ISSUE THREAD

**Issue by billkable** [ndwinton/tap-setup-scripts#1]
See [setup-tap.sh, line 243](https://github.com/ndwinton/tap-setup-scripts/blob/a17839ac1b9efc1f2fc67b8eb0b8d083aa342e40/setup-tap.sh#L243):

`DOCKERHUB_PASSWORD` should be `DOCKER_PASSWORD` according to[ kp documentation](https://docs.pivotal.io/build-service/1-2/managing-secrets.html#docker-hub-registry-secret) to avoid interactive login.

**Comment by ndwinton** [comment]
Thanks Bill! Now fixed and should be available if you update. I am going to do another install, this time with DockerHub, just to check but it'll be in a new version of the VM I'm uploading.
